[project]
authors = ["Gabryss <zeratul312@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "hexapod-calculator"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
marimo = ">=0.10.13,<0.11"
